# reasons you might want to use `environment.yaml` instead of `requirements.txt`:
# - pip installs packages in a loop, without ensuring dependencies across all packages
#   are fulfilled simultaneously, but conda achieves proper dependency control across
#   all packages
# - conda allows for installing packages without requiring certain compilers or
#   libraries to be available in the system, since it installs precompiled binaries
# in case of errors look here: https://pytorch.org/get-started/previous-versions/ 

name: interact

channels:
  - conda-forge
  - defaults

# it is strongly recommended to specify versions of packages installed through conda
# to avoid situation when version-unspecified packages install their latest major
# versions which can sometimes break things

# current approach below keeps the dependencies in the same major versions across all
# users, but allows for different minor and patch versions of packages where backwards
# compatibility is usually guaranteed

dependencies:
  - python=3.10

  - pip>=23
  - pip:
    - rootutils
    - hydra-core==1.3.2         # Hydra for config management
    - hydra-colorlog==1.2.0     # Allow colorful logging in Hydra
    - omegaconf==2.3.0          # Required by hydra-core
    - pandas==2.3.2
    - lxml==6.0.1
    - pymex==0.9.31
    - gitpython
    - transformers==4.55.4
    - beautifulsoup4==4.13.5
    - matplotlib==3.10.5
    - pinder==0.5.0
    - seaborn==0.13.2
    - statsmodels==0.14.6 # for plotting regression lines
    - gemmi==0.7.4
    - -e .