name: biogrid

url: https://downloads.thebiogrid.org/Download/BioGRID/Release-Archive/BIOGRID-4.4.248/BIOGRID-ALL-4.4.248.tab3.zip
output_dir: interactome/data_files/raw/biogrid
filename: BIOGRID-ALL-4.4.248.tab3.zip
task_name: download

mi_map_url: https://wiki.thebiogrid.org/lib/exe/fetch.php/biogrid_mi_mapping.xls
mi_map_filename: biogrid_mi_mapping.txt

delete_zip: true