name: hippie

url: https://cbdm-01.zdv.uni-mainz.de/~mschaefer/hippie/RS/experimental_scores.tsv
output_dir: interactome/data_files/raw/hippie
filename: experimental_scores.tsv
task_name: download

delete_zip: true