name: pepmlm

url:  https://zenodo.org/records/15122756/files/PepMLM_Train%20and%20Test%20Data.zip?download=1
output_dir: interactome/data_files/raw/pepmlm
filename: pepmlm_train_and_test_data.zip
task_name: download
unzip: true

delete_zip: true