# configs/download.yaml

defaults:
  - _self_
  - paths: default
  - download: intact
  - hydra: default  # ‚Üê tells Hydra to use the logging/output config

task_name: download
script_path: interactome/data/download/download_unzip.sh
