name: biogrid

input_file: interactome/data_files/raw/biogrid/BIOGRID-ALL-4.4.248.tab3.txt
example_output_dir: interactome/data_files/processed/biogrid/examples

output_dir: interactome/data_files/processed/biogrid